version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    healthcheck:
      test:
        [
          'CMD',
          'echo',
          'ruok',
          '|',
          'nc',
          'localhost',
          '2181',
          '|',
          'grep',
          'imok',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128M # Reduced memory for Zookeeper
          cpus: '0.1' # Reduced CPU to 10%

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: '-Xmx256m -Xms256m'
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 536870912
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 9092']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 384M # Reduced memory for Kafka
          cpus: '0.2' # Reduced CPU to 30%

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      POSTGRES_HOST: cat670aihdrkt1.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com
      POSTGRES_PORT: 5432
      POSTGRES_USER: u2lr3kth3p9dnr
      POSTGRES_PASSWORD: p648de9ce20f1f673c4f04e8ea861b9c4132060867bfdafe9f06d65486c8e3528
      POSTGRES_DB: d130isvvf07lsn
      KAFKA_BROKER: kafka:9092
      NETGSM_USERNAME: 8508409620
      NETGSM_PASSWORD: 1B,FE7D
      OPENAI_API_KEY: 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
      JWT_SECRET: SMSAI_SECRET
      PORT: 3001
      FRONTEND_URL: http://smsai.site:3002
      PAYTR_MERCHANT_ID: 562077
      PAYTR_MERCHANT_KEY: qGMad6R1dKyxC1mu
      PAYTR_MERCHANT_SALT: uEmZENZ3thnCJKg4
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 384M # Reduced memory for the app
          cpus: '0.4' # Reduced CPU to 40%

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M # Reduced memory for Kafka UI
          cpus: '0.1' # Reduced CPU to 10%
    profiles:
      - dev

volumes:
  postgres_data:
