version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    healthcheck:
      test:
        [
          'CMD',
          'echo',
          'ruok',
          '|',
          'nc',
          'localhost',
          '2181',
          '|',
          'grep',
          'imok',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128M # Reduced memory for Zookeeper
          cpus: '0.1' # Reduced CPU to 10%

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: '-Xmx256m -Xms256m'
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 536870912
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 9092']
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 384M # Reduced memory for Kafka
          cpus: '0.2' # Reduced CPU to 30%

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      POSTGRES_HOST: REDACTED
      POSTGRES_PORT: 5432
      POSTGRES_USER: REDACTED
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_DB: REDACTED
      KAFKA_BROKER: kafka:9092
      NETGSM_USERNAME: REDACTED
      NETGSM_PASSWORD: REDACTED
      OPENAI_API_KEY: REDACTED
      DEEPSEEK_API_KEY: REDACTED
      GOOGLE_API_KEY: REDACTED
      GOOGLE_API_KEY_FREE: REDACTED
      JWT_SECRET: REDACTED
      PORT: 3001
      FRONTEND_URL: https://www.smsai.site/
      PAYTR_MERCHANT_ID: REDACTED
      PAYTR_MERCHANT_KEY: REDACTED
      PAYTR_MERCHANT_SALT: REDACTED
      IYZICO_CALLBACK_URL: https://api.smsai.site/purchase/iyzicoCallback
      IYZICO_API_KEY: REDACTED
      IYZICO_SECRET_KEY: REDACTED
      IYZICO_TEST_API_KEY: REDACTED
      IYZICO_TEST_SECRET_KEY: REDACTED
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: REDACTED
      AWS_SECRET_ACCESS_KEY: REDACTED/
      CLOUDWATCH_LOG_GROUP: SmsAI
      CLOUDWATCH_LOG_STREAM: SmsAIBackend
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 384M # Reduced memory for the app
          cpus: '0.4' # Reduced CPU to 40%

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M # Reduced memory for Kafka UI
          cpus: '0.1' # Reduced CPU to 10%
    profiles:
      - dev

volumes:
  postgres_data:
