name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the files
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 2: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Debug: Print the current working directory and environment variables
            echo "Debug: Printing the current working directory on the EC2 instance"
            pwd
            ls -la

            # Check if the Smsai directory exists
            if [ -d "SmsAI" ]; then
              echo "SmsAI directory exists. Navigating to it."
              cd SmsAI
            else
              echo "SmsAI directory not found. Cloning the repository..."
              git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/satas20/SmsAI.git SmsAI && cd SmsAI
            fi

            # Reset and fetch the latest changes
            git fetch --all
            git reset --hard origin/master

            # Restart the application using Docker Compose
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found in SmsAI directory."
              exit 1
            fi
            docker compose down
            sleep 5
            echo "Cleaning docker system..."
            docker system prune -a -f
            sleep 5
            echo "Building and starting the application..."
            docker compose up --build -d
            sleep 5
            # Check if the application is running
            if [ "$(docker ps -q -f name=smsai-app)" ]; then
              echo "Application is running."
            else
              echo "Error: Application is not running."
              exit 1
            fi

            echo "Deployment completed successfully."
