name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the files
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 2: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Debug: Print the current working directory and environment variables
            echo "Debug: Printing the current working directory on the EC2 instance"
            pwd
            echo "Debug: Printing environment variables"
            env

            # Navigate to the Smsai directory or clone the repository if it doesn't exist
            cd Smsai || { 
              echo "Smsai directory not found, cloning...";
              git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/satas20/SmsAI.git Smsai && cd Smsai;
            }

            # Verify if the repository was cloned successfully
            if [ ! -d Smsai ]; then
              echo "Error: Smsai directory was not created. Cloning might have failed."
              exit 1
            fi

            # Reset and pull the latest changes
            git reset --hard
            git pull https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/satas20/SmsAI.git master

            # Install dependencies
            if [ ! -f package.json ]; then
              echo "Error: package.json not found in Smsai directory."
              exit 1
            fi
            npm install

            # Restart the application using Docker Compose
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found in Smsai directory."
              exit 1
            fi
            docker compose down
            sleep 5
            docker compose up --build -d
