name: Deploy to EC2

on:
  push:
    branches:
      - master # Trigger deployment on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Write the PEM Key to a File
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd Smsai || { echo "Smsai directory not found, cloning..."; git clone https://github.com/satas20/SmsAI.git Smsai && cd Smsai; }
            git reset --hard
            git pull origin master
            npm install
            docker compose down
            sleep 5
            docker compose up --build -d
          EOF
